[project]
name = "hawk_eye_agent"
version = "0.1.0"
description = "Knowledge Example using crewAI"
authors = [{ name = "Mike Plachta", email = "mike@crewai.com" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.152.0",
]

[project.scripts]
hawk_eye_agent = "hawk_eye_agent.main:run"
run_crew = "hawk_eye_agent.main:run"
train = "hawk_eye_agent.main:train"
replay = "hawk_eye_agent.main:replay"
test = "hawk_eye_agent.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
